name: rundeck-mcollective-nodes-plugin
version: 1.1
rundeckPluginVersion: 1.0
author: Chuck Scott
date: 9/14/2012
providers:
    - name:  rundeck-mcollective-nodes-resource-provider
      service: ResourceModelSource
      plugin-type: script
      script-interpreter: /usr/bin/ruby
      script-file: generate.rb
      script-args: mco rpc rpcutil -j inventory
      resource-format: resourcexml
      config:
         - type: String
           name: mco_command_line
           title:  mcollective client utility command line
           description: the command line used to produce node resource json data
           required: true
           default:  mco rpc --dm mongo rpcutil -j inventory
